package stockapp;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import static stockapp.NumberOfStocks1.NumberStocks;
import static stockapp.BuyStocks.CompanyStock;
import static stockapp.BuyStocks.CompanyName;
import static stockapp.RemainingBalance1.RemBal;

import static stockapp.Server.dlf;
import static stockapp.Server.colgate;
import static stockapp.Server.lupin;
import static stockapp.Server.hero;
import static stockapp.Server.tata;

/**
 *
 * @author SHREE
 */
public class BuyStocks2 extends javax.swing.JFrame {

    //String bal = RemBal.getText();
    int numStocks = Integer.parseInt(NumberStocks);
    int getamount = Integer.parseInt(CompanyStock);
    //int rembal = Integer.parseInt(bal);
    
    
    int total = numStocks * getamount;
    
    String Total = String.valueOf(total);
    
    /**
     * 
     * Creates new form Buystocks1
     */
    
    public BuyStocks2() {
        initComponents();
        Connect();
    }
    
    Connection con;
    PreparedStatement pst;
    DefaultTableModel df;
   
    
    
    public void Connect()
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/stocktrading", "root", "");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TotalAmount = new javax.swing.JLabel();
        confirm = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("TOTAL AMOUNT DEDUCTED - ");

        TotalAmount.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        TotalAmount.setText(Total);

        confirm.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        confirm.setText("CONFIRM");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    confirmActionPerformed(evt);
                } catch (SQLException ex) {
                    Logger.getLogger(BuyStocks2.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(TotalAmount))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(confirm)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TotalAmount))
                .addGap(27, 27, 27)
                .addComponent(confirm)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        
        setLocationRelativeTo(null);

        pack();
    }// </editor-fold>                        

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {   
        
    
        //rembal = rembal - total;
        //RemBal.setText(String.valueOf(rembal));
        RemainingBalance1 obj = new RemainingBalance1();
        try
        {
            
            String balance = null;
            String query = "SELECT Remaining_Balance from money_transactions";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            
            while(rs.next())
            {
                balance = rs.getString("Remaining_Balance");
            }
            
            int bal = Integer.parseInt(balance) - total;
            RemBal.setText(String.valueOf(bal));
            
            pst = con.prepareStatement("insert into money_transactions(Action, Amount, Remaining_Balance)values(?, ?, ?)");
            pst.setString(1, "Debit");
            pst.setString(2, Total);
            pst.setString(3, String.valueOf(bal));
            
            pst.executeUpdate();
            
            
            JOptionPane.showMessageDialog(this, Total + " Successfully debited from your demat account!");
            
            pst = con.prepareStatement("insert into stock_transactions(Action, Company_Name, Stock_Amount, Stock_Number, Amount)values(?, ?, ?, ?, ?)");
            pst.setString(1, "Buy");
            pst.setString(2, CompanyName);
            if("DLF".equals(CompanyName))
                pst.setString(3, dlf);
            if("COLGATE-PALMOLIVE".equals(CompanyName))
                pst.setString(3, colgate);
            if("TATA MOTORS".equals(CompanyName))
                pst.setString(3, tata);
            if("HERO MOTOCORP".equals(CompanyName))
                pst.setString(3, hero);
            if("LUPIN".equals(CompanyName))
                pst.setString(3, lupin);
               
            pst.setString(4, NumberStocks);
            pst.setString(5, Total);
            
            pst.executeUpdate();
            
            
            
            pst = con.prepareStatement("insert into availble_stocks(Company_Name, Stock_Number)values(?,?)");
            pst.setString(1, CompanyName);
            pst.setString(2, NumberStocks);
            
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Stock transaction table updated!!");
        }
        
        catch(SQLException ex)
        {
            Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
        }
        //obj.setVisible(true);
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buystocks1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buystocks1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buystocks1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buystocks1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buystocks1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel TotalAmount;
    private javax.swing.JButton confirm;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration                   
}
