/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package stockapp;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.awt.*;
import static stockapp.BuyStocks.CompanyName;

import static stockapp.SellStocks.comname;
import static stockapp.SellStocks.stocksnum;
import static stockapp.SellStocks.stockprice;
//import static stockapp.BuyStocks.CompanyStock;
import static stockapp.RemainingBalance1.RemBal;
import static stockapp.NumberOfStocks1.num;
import static stockapp.Server.dlf;
import static stockapp.Server.colgate;
import static stockapp.Server.lupin;
import static stockapp.Server.hero;
import static stockapp.Server.tata;

/**
 *
 * @author SHREE
 */
public class SellStocks3 extends javax.swing.JFrame {

    
    int stocknum = Integer.parseInt(stocksnum);
    
    
    
            
    int getamount = Integer.parseInt(stockprice);
    //int getamount = 460;
    //int stocknum = Integer.parseInt("2");
    //int getamount = Integer.parseInt("460");
    
    int total = stocknum * getamount;
    
    String Total = String.valueOf(total);
    /**
     * Creates new form SellStocks1
     */
    public SellStocks3() {
        initComponents();
        Connect();
    }
    
    Connection con, con1;
    PreparedStatement pst, pst1, pst2;
    DefaultTableModel df, df1;
   
    
    
    public void Connect()
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/stocktrading", "root", "");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TotalAmount = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        price = new javax.swing.JLabel();
        number = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("TOTAL AMOUNT ADDED - ");

        TotalAmount.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        TotalAmount.setText(Total);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton1.setText("CONFIRM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        price.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        price.setText(stockprice);

        number.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        number.setText(stocksnum);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TotalAmount))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(price)
                        .addGap(56, 56, 56)
                        .addComponent(number)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TotalAmount))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price)
                    .addComponent(number))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        RemainingBalance1 obj = new RemainingBalance1();
        try
        {
            String balance = null;
            String query = "SELECT Remaining_Balance from money_transactions";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            
            while(rs.next())
            {
                balance = rs.getString("Remaining_Balance");
            }
            
            int bal = Integer.parseInt(balance) + total;
            RemBal.setText(String.valueOf(bal));
            
            pst = con.prepareStatement("insert into money_transactions(Action, Amount, Remaining_Balance)values(?, ?, ?)");
            pst.setString(1, "Credit");
            pst.setString(2, Total);
            pst.setString(3, String.valueOf(bal));
            
            pst.executeUpdate();
            
            pst1 = con.prepareStatement("insert into stock_transactions(Action, Company_Name, Stock_Amount, Stock_Number, Amount)values(?, ?, ?, ?, ?)");
            pst1.setString(1, "Sell");
            pst1.setString(2, comname);
            
            
            
            if("DLF".equals(CompanyName))
                pst1.setString(3, dlf);
            if("COLGATE-PALMOLIVE".equals(CompanyName))
                pst1.setString(3, colgate);
            if("TATA MOTORS".equals(CompanyName))
                pst1.setString(3, tata);
            if("HERO MOTOCORP".equals(CompanyName))
                pst1.setString(3, hero);
            if("LUPIN".equals(CompanyName))
                pst.setString(3, lupin);
            
            
            pst1.setString(4, stocksnum);
            pst1.setString(5, Total);
            
            pst1.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Your request for sell has been placed!!");
            
            //Connection con2 = DriverManager.getConnection("jdbc:mysql://localhost/stocktrading", "root", "");
            String q = "update availble_stocks set Stock_Number=? where Company_Name=?";
            
            int num1 = num - stocknum;
            String numsto = String.valueOf(num1);
            //int num1 = Integer.parseInt(num);
            String com = comname;
            //int am = total - (getamount * num1);
            
            //String am1 = String.valueOf(am);
            
            pst2 = con.prepareStatement(q);
            pst2.setString(1, numsto);
            pst2.setString(2, com);
            
            
            pst2.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Your request for sell has been placed!!");
        } 
        
        catch(SQLException ex)
        {
            Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellStocks1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellStocks1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellStocks1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellStocks1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellStocks1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel TotalAmount;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel number;
    private javax.swing.JLabel price;
    // End of variables declaration                   
}
